In [1]:
import pandas as pd

In [2]:
columns = ['Timestamp', 'x accelerometer', 'y accelerometer', 
           
           'z accelerometer', 'x gyro', 'y gyro', 'z gyro', 'surface']

In [3]:
### Grass

grass_23_df = pd.read_csv('../datasets/combined/23_GSW_trimmed.csv', header = None)

grass_23_df.columns = columns

In [4]:
grass_24_df = pd.read_csv('../datasets/combined/24_GSW_trimmed.csv')

grass_24_df['surface'] = 'grass'

grass_24_df.columns = columns

In [5]:
grass_25_df = pd.read_csv('../datasets/combined/25_GSW_trimmed.csv')

In [6]:
grass_df = pd.concat([grass_23_df, grass_24_df, grass_25_df], axis = 0)

In [7]:
grass_df

,Timestamp,x accelerometer,y accelerometer,z accelerometer,x gyro,y gyro,z gyro,surface
0,2024-03-21 13:42:42,-0.028809,-0.299805,-0.958252,1.281738,1.068115,4.928589,grass
1,2024-03-21 13:42:42,-0.016357,-0.300293,-0.949219,1.373291,0.991821,5.004883,grass
2,2024-03-21 13:42:42,-0.023438,-0.287109,-0.953125,1.068115,0.717163,4.745483,grass
3,2024-03-21 13:42:42,-0.027832,-0.287354,-0.948730,0.839233,0.335693,4.699707,grass
4,2024-03-21 13:42:42,0.001465,-0.277832,-0.946533,0.946045,0.183105,4.608154,grass
...,...,...,...,...,...,...,...,...
5595,2024-03-21 13:52:12.126,0.015137,-0.169922,-0.995117,2.227783,-1.846313,1.174927,grass
5596,2024-03-21 13:52:12.135,0.016357,-0.173096,-0.998047,2.212524,-1.815796,1.007080,grass
5597,2024-03-21 13:52:12.145,0.027832,-0.173584,-1.001709,2.090454,-1.647949,0.686645,grass
5598,2024-03-21 13:52:12.155,0.027344,-0.187988,-1.001953,1.754761,-1.403808,0.473022,grass
5599,2024-03-21 13:52:12.165,0.025146,-0.194824,-1.017822,1.464844,-1.205444,-0.244141,grass

In [8]:
grass_df['surface'].unique()

array(['grass'], dtype=object)

In [9]:
grass_df.drop(['Timestamp'], axis = 1, inplace = True)

grass_df

,x accelerometer,y accelerometer,z accelerometer,x gyro,y gyro,z gyro,surface
0,-0.028809,-0.299805,-0.958252,1.281738,1.068115,4.928589,grass
1,-0.016357,-0.300293,-0.949219,1.373291,0.991821,5.004883,grass
2,-0.023438,-0.287109,-0.953125,1.068115,0.717163,4.745483,grass
3,-0.027832,-0.287354,-0.948730,0.839233,0.335693,4.699707,grass
4,0.001465,-0.277832,-0.946533,0.946045,0.183105,4.608154,grass
...,...,...,...,...,...,...,...
5595,0.015137,-0.169922,-0.995117,2.227783,-1.846313,1.174927,grass
5596,0.016357,-0.173096,-0.998047,2.212524,-1.815796,1.007080,grass
5597,0.027832,-0.173584,-1.001709,2.090454,-1.647949,0.686645,grass
5598,0.027344,-0.187988,-1.001953,1.754761,-1.403808,0.473022,grass
5599,0.025146,-0.194824,-1.017822,1.464844,-1.205444,-0.244141,grass

In [10]:
grass_df.to_csv('../datasets/final/GSW.csv', index = False)

In [11]:
### Tile

tile_11_df = pd.read_csv('../datasets/combined/11_TS_trimmed.csv')

tile_11_df['surface'] = 'tile'

tile_11_df.columns = columns

In [12]:
tile_18_df = pd.read_csv('../datasets/combined/18_TS_trimmed.csv', header = None)

tile_18_df.columns = columns

In [13]:
tile_21_df = pd.read_csv('../datasets/combined/21_TS_trimmed.csv')

In [14]:
tile_df = pd.concat([tile_11_df, tile_18_df, tile_21_df], axis = 0)

In [15]:
tile_df

,Timestamp,x accelerometer,y accelerometer,z accelerometer,x gyro,y gyro,z gyro,surface
0,2024-03-20 09:35:12.340,0.092773,-0.054932,-0.982910,1.892090,-0.854492,-0.213623,tile
1,2024-03-20 09:35:12.350,-0.007324,-0.062012,-1.098145,-0.061035,1.083374,-0.244141,tile
2,2024-03-20 09:35:12.359,-0.054932,-0.028564,-0.941406,0.152588,0.045776,-0.076294,tile
3,2024-03-20 09:35:12.369,0.028809,-0.003174,-0.937012,1.632690,-0.900268,-0.946045,tile
4,2024-03-20 09:35:12.380,0.077637,-0.110596,-1.071045,1.983642,1.373291,-0.869751,tile
...,...,...,...,...,...,...,...,...
5195,2024-03-20 10:22:45.130,0.016602,-0.080322,-0.970215,1.251221,0.396728,2.548218,tile
5196,2024-03-20 10:22:45.139,-0.008789,-0.092773,-1.009033,1.617432,0.656128,3.036499,tile
5197,2024-03-20 10:22:45.150,0.013428,-0.066162,-0.994141,1.907349,0.717163,3.158569,tile
5198,2024-03-20 10:22:45.159,-0.018311,-0.072998,-1.035645,1.754761,0.686645,2.975464,tile
5199,2024-03-20 10:22:45.169,-0.002197,-0.045898,-1.023193,1.922607,0.106812,3.265381,tile

In [16]:
tile_df['surface'].unique()

array(['tile'], dtype=object)

In [17]:
tile_df.drop(['Timestamp'], axis = 1, inplace = True)

tile_df

,x accelerometer,y accelerometer,z accelerometer,x gyro,y gyro,z gyro,surface
0,0.092773,-0.054932,-0.982910,1.892090,-0.854492,-0.213623,tile
1,-0.007324,-0.062012,-1.098145,-0.061035,1.083374,-0.244141,tile
2,-0.054932,-0.028564,-0.941406,0.152588,0.045776,-0.076294,tile
3,0.028809,-0.003174,-0.937012,1.632690,-0.900268,-0.946045,tile
4,0.077637,-0.110596,-1.071045,1.983642,1.373291,-0.869751,tile
...,...,...,...,...,...,...,...
5195,0.016602,-0.080322,-0.970215,1.251221,0.396728,2.548218,tile
5196,-0.008789,-0.092773,-1.009033,1.617432,0.656128,3.036499,tile
5197,0.013428,-0.066162,-0.994141,1.907349,0.717163,3.158569,tile
5198,-0.018311,-0.072998,-1.035645,1.754761,0.686645,2.975464,tile
5199,-0.002197,-0.045898,-1.023193,1.922607,0.106812,3.265381,tile

In [18]:
tile_df.to_csv('../datasets/final/TS.csv', index = False)

In [19]:
### Asphalt

asphalt_15_df = pd.read_csv('../datasets/combined/15_AFW_trimmed.csv', header = None)

asphalt_15_df.columns = columns

In [20]:
asphalt_19_df = pd.read_csv('../datasets/combined/19_AFW_trimmed.csv')

In [21]:
asphalt_22_df = pd.read_csv('../datasets/combined/22_AFW_trimmed.csv')

asphalt_22_df['surface'] = 'asphalt'

asphalt_22_df.columns = columns

In [22]:
asphalt_df = pd.concat([asphalt_15_df, asphalt_19_df, asphalt_22_df], axis = 0)

In [23]:
asphalt_df

,Timestamp,x accelerometer,y accelerometer,z accelerometer,x gyro,y gyro,z gyro,surface
0,2024-03-20 9:54:37,-0.087402,0.024414,-0.899170,-1.220703,-0.686645,-0.961304,asphalt
1,2024-03-20 9:54:37,-0.162354,0.053223,-0.816895,-1.525879,-1.281738,0.488281,asphalt
2,2024-03-20 9:54:37,-0.010254,0.014160,-1.160156,0.717163,-0.503540,0.183105,asphalt
3,2024-03-20 9:54:37,0.208252,0.027588,-1.086426,-0.473022,0.625610,-1.007080,asphalt
4,2024-03-20 9:54:37,-0.027832,-0.030029,-0.930908,-3.982544,2.029419,-0.228882,asphalt
...,...,...,...,...,...,...,...,...
4866,2024-03-20 10:28:31.889,0.010986,-0.072021,-1.009033,0.671387,0.228882,0.167847,asphalt
4867,2024-03-20 10:28:31.899,0.010498,-0.071289,-1.008301,0.671387,0.213623,0.061035,asphalt
4868,2024-03-20 10:28:31.909,0.008057,-0.069824,-1.006836,0.656128,0.152588,0.183105,asphalt
4869,2024-03-20 10:28:31.920,0.007813,-0.068604,-1.007813,0.686645,0.228882,0.198364,asphalt
4870,2024-03-20 10:28:31.930,0.008545,-0.070557,-1.005859,0.701904,0.228882,0.091553,asphalt

In [24]:
asphalt_df['surface'].unique()

array(['asphalt'], dtype=object)

In [25]:
asphalt_df.drop(['Timestamp'], axis = 1, inplace = True)

asphalt_df

,x accelerometer,y accelerometer,z accelerometer,x gyro,y gyro,z gyro,surface
0,-0.087402,0.024414,-0.899170,-1.220703,-0.686645,-0.961304,asphalt
1,-0.162354,0.053223,-0.816895,-1.525879,-1.281738,0.488281,asphalt
2,-0.010254,0.014160,-1.160156,0.717163,-0.503540,0.183105,asphalt
3,0.208252,0.027588,-1.086426,-0.473022,0.625610,-1.007080,asphalt
4,-0.027832,-0.030029,-0.930908,-3.982544,2.029419,-0.228882,asphalt
...,...,...,...,...,...,...,...
4866,0.010986,-0.072021,-1.009033,0.671387,0.228882,0.167847,asphalt
4867,0.010498,-0.071289,-1.008301,0.671387,0.213623,0.061035,asphalt
4868,0.008057,-0.069824,-1.006836,0.656128,0.152588,0.183105,asphalt
4869,0.007813,-0.068604,-1.007813,0.686645,0.228882,0.198364,asphalt
4870,0.008545,-0.070557,-1.005859,0.701904,0.228882,0.091553,asphalt

In [26]:
asphalt_df.to_csv('../datasets/final/AFW.csv', index = False)

In [27]:
### Concrete

concrete_13_df = pd.read_csv('../datasets/combined/13_CFD_trimmed.csv')

In [28]:
concrete_17_df = pd.read_csv('../datasets/combined/17_CFD_trimmed.csv')

concrete_17_df['surface'] = 'concrete'

concrete_17_df.columns = columns

In [29]:
concrete_20_df = pd.read_csv('../datasets/combined/20_CFD_trimmed.csv', header = None)

concrete_20_df.columns = columns

In [30]:
concrete_df = pd.concat([concrete_13_df, concrete_17_df, concrete_20_df], axis = 0)

In [31]:
concrete_df

,Timestamp,x accelerometer,y accelerometer,z accelerometer,x gyro,y gyro,z gyro,surface
0,2024-03-20 09:42:57.299,-0.072754,-0.024170,-1.005615,0.595093,0.823975,0.595093,concrete
1,2024-03-20 09:42:57.310,-0.065186,-0.037354,-1.033447,1.403808,0.747681,0.350952,concrete
2,2024-03-20 09:42:57.319,-0.029785,-0.037354,-1.014160,1.296997,0.152588,0.534058,concrete
3,2024-03-20 09:42:57.330,-0.001221,-0.033203,-1.005859,0.961304,0.015259,0.701904,concrete
4,2024-03-20 09:42:57.340,0.037842,-0.018066,-1.007813,1.266479,0.564575,0.701904,concrete
...,...,...,...,...,...,...,...,...
5105,2024-03-20 10:18:32,0.130615,-0.036621,-1.022705,3.219604,1.480102,-3.692627,concrete
5106,2024-03-20 10:18:32,0.036865,-0.011963,-1.070557,0.595093,2.807617,-3.936767,concrete
5107,2024-03-20 10:18:32,-0.125977,-0.032959,-0.997559,-0.015259,2.105713,-4.287720,concrete
5108,2024-03-20 10:18:32,-0.026855,-0.000244,-0.992676,0.854492,-0.473022,-4.379272,concrete
5109,2024-03-20 10:18:32,0.118652,-0.044189,-0.999512,1.403808,0.015259,-5.340576,concrete

In [32]:
concrete_df['surface'].unique()

array(['concrete'], dtype=object)

In [33]:
concrete_df.drop(['Timestamp'], axis = 1, inplace = True)

concrete_df

,x accelerometer,y accelerometer,z accelerometer,x gyro,y gyro,z gyro,surface
0,-0.072754,-0.024170,-1.005615,0.595093,0.823975,0.595093,concrete
1,-0.065186,-0.037354,-1.033447,1.403808,0.747681,0.350952,concrete
2,-0.029785,-0.037354,-1.014160,1.296997,0.152588,0.534058,concrete
3,-0.001221,-0.033203,-1.005859,0.961304,0.015259,0.701904,concrete
4,0.037842,-0.018066,-1.007813,1.266479,0.564575,0.701904,concrete
...,...,...,...,...,...,...,...
5105,0.130615,-0.036621,-1.022705,3.219604,1.480102,-3.692627,concrete
5106,0.036865,-0.011963,-1.070557,0.595093,2.807617,-3.936767,concrete
5107,-0.125977,-0.032959,-0.997559,-0.015259,2.105713,-4.287720,concrete
5108,-0.026855,-0.000244,-0.992676,0.854492,-0.473022,-4.379272,concrete
5109,0.118652,-0.044189,-0.999512,1.403808,0.015259,-5.340576,concrete

In [34]:
concrete_df.to_csv('../datasets/final/CFD.csv', index = False)

In [35]:
### Stones

stone_12_df = pd.read_csv('../datasets/combined/12_SCW_trimmed.csv', header = None)

stone_12_df.columns = columns

In [36]:
stone_14_df = pd.read_csv('../datasets/combined/14_SCW_trimmed.csv')

stone_14_df['surface'] = 'stones'

stone_14_df.columns = columns

In [37]:
stone_16_df = pd.read_csv('../datasets/combined/16_SCW_trimmed.csv')

In [38]:
stone_df = pd.concat([stone_12_df, stone_14_df, stone_16_df], axis = 0)

In [39]:
stone_df

,Timestamp,x accelerometer,y accelerometer,z accelerometer,x gyro,y gyro,z gyro,surface
0,2024-03-20 9:38:45,-0.179688,-0.122314,-0.964600,-2.655029,1.342773,2.456665,stones
1,2024-03-20 9:38:45,-0.166748,-0.115967,-0.987305,-3.677368,-0.045776,4.333496,stones
2,2024-03-20 9:38:45,-0.086426,-0.140137,-1.041260,-1.312256,0.152588,5.172729,stones
3,2024-03-20 9:38:45,-0.086426,-0.134277,-0.964600,-1.586914,0.122070,6.103515,stones
4,2024-03-20 9:38:45,0.006592,-0.101563,-0.971924,-2.059937,-1.266479,6.088256,stones
...,...,...,...,...,...,...,...,...
4695,2024-03-20 10:00:23.149,-0.275391,-0.194580,-0.808838,-10.696410,6.469726,-5.599975,stones
4696,2024-03-20 10:00:23.159,-0.298828,-0.199463,-0.806396,-9.216309,5.065917,-6.408691,stones
4697,2024-03-20 10:00:23.170,-0.181641,-0.164063,-0.912842,-7.690429,2.929687,-7.095336,stones
4698,2024-03-20 10:00:23.180,-0.191162,-0.209961,-1.000488,-2.578735,2.624511,-5.661010,stones
4699,2024-03-20 10:00:23.190,-0.259033,-0.280273,-1.057617,-0.686645,2.456665,-4.364014,stones

In [40]:
stone_df['surface'].unique()

array(['stones'], dtype=object)

In [41]:
stone_df.drop(['Timestamp'], axis = 1, inplace = True)

stone_df

,x accelerometer,y accelerometer,z accelerometer,x gyro,y gyro,z gyro,surface
0,-0.179688,-0.122314,-0.964600,-2.655029,1.342773,2.456665,stones
1,-0.166748,-0.115967,-0.987305,-3.677368,-0.045776,4.333496,stones
2,-0.086426,-0.140137,-1.041260,-1.312256,0.152588,5.172729,stones
3,-0.086426,-0.134277,-0.964600,-1.586914,0.122070,6.103515,stones
4,0.006592,-0.101563,-0.971924,-2.059937,-1.266479,6.088256,stones
...,...,...,...,...,...,...,...
4695,-0.275391,-0.194580,-0.808838,-10.696410,6.469726,-5.599975,stones
4696,-0.298828,-0.199463,-0.806396,-9.216309,5.065917,-6.408691,stones
4697,-0.181641,-0.164063,-0.912842,-7.690429,2.929687,-7.095336,stones
4698,-0.191162,-0.209961,-1.000488,-2.578735,2.624511,-5.661010,stones
4699,-0.259033,-0.280273,-1.057617,-0.686645,2.456665,-4.364014,stones

In [42]:
stone_df.to_csv('../datasets/final/SCW.csv', index = False)